Turn off FMA option for the intel compiler on Derecho
ESMCI/ccs_config_cesm pull request #121
Opened 2023-09-15 17:08 UTC by sjsprecious

This PR adds the `-no-fma` option to the intel compiler on Derecho. This makes sure that the ensemble consistency test is passed when using the `intel/2023` compiler on Derecho for the test simulations and comparing the results to the baseline generated on Cheyenne with `intel/19.1.1`. See more discussions here: https://github.com/ESCOMP/CAM/issues/883.

2023-09-15 17:13 UTC, jedwards4b requested changes
Why do we have this in the machine specific file instead of the generic intel.cmake file?

2023-09-15 17:17 UTC, sjsprecious commented
I guess the options like "--host=cray" and "-march=core-avx2" are specific to Derecho (Cray machine and AMD CPU)?

2023-09-15 17:18 UTC, jedwards4b commented
Can I push that change back to your PR?  Move no-fma flag to generic intel.cmake file.

2023-09-15 17:22 UTC, sjsprecious commented
Oh, sorry that I misunderstand your point. You mean we should turn off FMA whenever we use the intel compiler on any machine? That is fine with me but I am not sure if other people want to leave it on for their machines (e.g., people do no use ECT for verification).

2023-09-15 17:54 UTC, sjsprecious commented
Machines like **constance** and **izumi** all turn on FMA by default. Moving `-no-fma` to the **intel.cmake** file will break the regression test on those machines and it may not be desirable.

2023-09-15 17:57 UTC, jedwards4b commented
Are we running ect on those systems?  Seems like the ect test confirms that we should not be using fma on any system.

2023-09-15 18:04 UTC, sjsprecious commented
I agreed that based on ECT, we should not use FMA for any system. I do not have access to those systems but I assume that they will run some regressions tests like `aux_cam` for BFB. If we add FMA to the generic file, their tests will fail and they may not want that if they do not trust ECT like we do. This is my concern.

2023-09-15 18:06 UTC, briandobbins commented
If it fails the ECT with FMA on, I'd be inclined to think it should be off
everywhere, no?  Not just the systems where we run the ECT.  Failing means
it's a statistically different climatology.

  - Brian


On Fri, Sep 15, 2023 at 12:04 PM Jian Sun ***@***.***> wrote:

> I agreed that based on ECT, we should not use FMA for any system. I do not
> have access to those systems but I assume that they will run some
> regressions tests like aux_cam for BFB. If we add FMA to the generic
> file, their tests will fail and they may not want that if they do not trust
> ECT like we do. This is my concern.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/ESMCI/ccs_config_cesm/pull/121#issuecomment-1721655897>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ACL2HPJ7CNWF2QOFWVSEC2DX2SKEHANCNFSM6AAAAAA42C76F4>
> .
> You are receiving this because you are subscribed to this thread.Message
> ID: ***@***.***>
>

2023-09-15 18:08 UTC, jedwards4b commented
We will mark the PR as answer changing so that people understand that baselines may fail.

2023-09-15 18:14 UTC, sjsprecious commented
Thanks @jedwards4b and @briandobbins for your comments. That sounds good to me.

My last comment is how we could make sure that `-no-fma` is added as the last option? Each system applies some specific flags and I do not want the `-no-fma` flag to be overwritten by other optimization flags.

2023-09-15 19:07 UTC, sjsprecious commented
A quick test on Derecho by moving `-no-fma` from the machine specific file to the generic intel file passes the ECT. Thus I will move on to do what @jedwards4b and @briandobbins suggested here.

If anyone finds out an issue about the changes here, they can always modify the flags specifically for their own system.

2023-09-15 19:37 UTC, jedwards4b requested changes

2023-09-15 19:37 UTC, jedwards4b commented on machines/cmake_macros/intel.cmake
>  endif()
I think that you shouldn't do this seperately for DEBUG=TRUE vs DEBUG=FALSE.   You can add it once at line 1 or if you want to make sure it's after the other flags add another line after 10 
string(APPEND CFLAGS "-no-fma")

2023-09-15 19:43 UTC, sjsprecious commented on machines/cmake_macros/intel.cmake
>  endif()
Thanks Jim. I just updated those files.

2023-09-15 19:43 UTC, jedwards4b approved these changes

2023-09-15 19:43 UTC, merged

2023-09-15 22:32 UTC, fischer-ncar commented
It looks like the FMA option was also causing my ERP/PEM/ERC tests to fail.  I'll need to do more ERP/PEM/ERC testing.

2023-09-15 22:55 UTC, jedwards4b commented
That totally makes sense since changing task count with fma enabled will change answers.

2023-09-16 01:52 UTC, sjsprecious commented
@jedwards4b can you explain more about why changing task count with FMA enabled will change answers? I thought changing task count just affected the domain decomposition.

2023-09-16 13:55 UTC, jedwards4b commented
I misspoke there - I was thinking about vector math and how using different pelayouts changes the length of the vectors - but that doesn't have anything to do with FMA.

2023-09-16 21:05 UTC, sjsprecious commented
Thanks Jim for your clarification. I assumed Chris was doing the ERP test on Derecho and my understanding was that its failure should not be caused by the FMA option. But it seems that turning off FMA on Derecho passes the ERP test somehow?

2023-09-16 22:13 UTC, jedwards4b commented
Maybe we should confirm that with another test?

2023-09-17 03:29 UTC, sjsprecious commented
Agreed and I think Chris is already working on it? I would like to let Chris update more details here in case I have a misunderstanding.

2023-09-18 16:44 UTC, fischer-ncar commented
I reran the prealpha tests over the weekend.  These following tests were all failing before FMA was turned off.

 
    PASS ERP_Ld3_Vnuopc.f09_f09_mg17.FCfireHIST.derecho_intel.cam-outfrq1d COMPARE_base_rest
    PASS ERP_Ln9_Vnuopc.f09_f09_mg17.F1850.derecho_intel.cam-outfrq9s COMPARE_base_rest
    PASS ERP_Ln9_Vnuopc.f09_f09_mg17.F2000climo.derecho_intel.cam-outfrq9s COMPARE_base_rest
    PASS ERP_Ln9_Vnuopc.f09_f09_mg17.F2000dev.derecho_intel.cam-outfrq9s_mg3 COMPARE_base_rest
    PASS ERP_Ln9_Vnuopc.f09_f09_mg17.F2010climo.derecho_intel.cam-outfrq9s COMPARE_base_rest
    PASS ERP_Ln9_Vnuopc.f09_f09_mg17.FHIST_BGC.derecho_intel.cam-outfrq9s COMPARE_base_rest
    PASS ERP_Ln9_Vnuopc.f09_f09_mg17.FHIST.derecho_intel.cam-outfrq9s COMPARE_base_rest
    PASS ERP_Ln9_Vnuopc.f09_f09_mg17.FTJ16.derecho_intel.cam-outfrq9s COMPARE_base_rest

2023-09-18 19:27 UTC, sjsprecious commented
Thanks Chris for posting these new results. So turning off FMA does help pass the ERP tests on Derecho somehow.

Are there any other type of tests besides ERP that also pass due to the disablement of FMA?