Derecho runs requesting >64 jobs go to main, not develop
ESMCI/ccs_config_cesm pull request #185
Opened 2024-08-23 16:48 UTC by samsrabin

So, e.g., tests with `128x1` go to main instead of develop. However, `64x2` would still go to develop—not sure if that's what we want.

Resolves #182.

2024-08-23 16:54 UTC, samsrabin commented
Sending `64x2` tests to main can be achieved by changing the cutoff from `64|65` to `63|64`.

2024-09-09 16:43 UTC, samsrabin commented
@jedwards4b Any chance we could get this in soon? It'd help a lot with CTSM testing.

2024-09-09 16:50 UTC, jedwards4b requested changes

2024-09-09 16:50 UTC, jedwards4b commented on machines/derecho/config_batch.xml
> +    <queue walltimemax="12:00:00" nodemin="64" nodemax="318464" >main</queue>
@samsrabin the statement at line 16 is incorrect - that is a minimum number of nodes, not a minimum number of tasks.

2024-09-09 18:02 UTC, samsrabin commented
🤦‍♂️ fixed!

2024-09-09 18:51 UTC, jedwards4b approved these changes
This will cause any job using more that 63 tasks to go to the main queue - is that what you want?

2024-09-09 21:04 UTC, samsrabin commented
For me, yes. We have a number of 128x1 and 64x2 tests in the CTSM test suite. Because a user can only use up to 256 `develop` queue tasks at a time, we'd prefer such tests to go to `main`, keeping our `develop` allotment freer.

2024-09-09 22:55 UTC, merged