Add `lobata` workstation to configuration files
ESMCI/ccs_config_cesm pull request #50
Opened 2022-07-07 22:43 UTC by glemieux

This PR adds the necessary configuration files and entries to include the FATES development workstation, `lobata` as a supported machine.  It also removes the now retired `lawrencium-lr2` entry.

2022-07-07 22:55 UTC, glemieux commented
I have one task that I want to complete before this is ready: I'm not sure whether how want to set the `--map-by` option and what the deciding criteria would be.  `lobata` has numa nodes, so I'd like to be able to distribute tasks across those nodes.

2022-07-08 16:20 UTC, glemieux commented
Note that due to issue with use of `source` by case.py to initialize `modules`, I had to cherry-pick the fix for https://github.com/ESMCI/cime/issues/4260 from https://github.com/ESMCI/cime/releases/tag/cime6.0.40.  @ekluzek created a branch tag to accompany this PR, both of which will be included in https://github.com/ESCOMP/CTSM/pull/1515.

2022-07-15 15:45 UTC, ekluzek requested changes
OK, there's two questions I have here that I'd like you to look at.

But, in general this looks great to me as far as I can tell.

2022-07-15 15:45 UTC, ekluzek commented on machines/cmake_macros/gnu_lobata.cmake
> +endif()
There is an "else" syntax in cmake that seems like it should be used here.

2022-07-15 15:45 UTC, ekluzek commented on machines/cmake_macros/gnu_lobata.cmake
> +endif()
Wait, what's the difference between these two? isn't the second one always going to happen?

2022-07-15 15:51 UTC, ekluzek commented
@jedwards4b and @fischer-ncar could one of you code review this PR and then merge it in? I ask two questions of @glemieux as well and it would be good to see what you think of my questions. @glemieux will take a closer look at those as well.

2022-07-15 16:07 UTC, glemieux commented on machines/cmake_macros/gnu_lobata.cmake
> +endif()
Good point.  This and the compiler configuration file are likely not particularly optimized as they have been inherited from previous machines and builds.  In fact the path `set` commands can probably be removed since `Lobata` uses modules to handle that now.  I'll review this.  I may need to catch up with you via chat or google meet to ask some other questions.

2022-07-15 17:05 UTC, ekluzek approved these changes

2022-07-15 17:06 UTC, ekluzek commented on machines/cmake_macros/gnu_lobata.cmake
> +endif()
Looks good.

2022-07-15 22:30 UTC, fischer-ncar approved these changes

2022-07-15 22:30 UTC, merged