Gpu improvements
ESMCI/ccs_config_cesm pull request #66
Opened 2022-11-03 14:44 UTC by jedwards4b

Remove special definitions for gpu enabled compilers.  WIP

2022-11-03 15:16 UTC, fischer-ncar approved these changes

2022-11-03 15:42 UTC, sjsprecious requested changes

2022-11-03 15:42 UTC, sjsprecious commented on machines/cmake_macros/nvhpc_casper.cmake
> +endif()
can we issue an error message and exit the compilation for a configuration other than V100 GPU and OpenACC? In this way we won't accidentally compile the code with undesired flags.

2022-11-03 15:42 UTC, sjsprecious commented on machines/cmake_macros/nvhpc_casper.cmake
> +endif()
Also, we could add the A100 GPU and OpenACC configuration here with the flag ` -acc -gpu=cc80,lineinfo,nofma -Minfo=accel `.

2022-11-03 15:42 UTC, sjsprecious commented on machines/config_batch.xml
>        <directive default="/bin/bash" > -S /glade/u/apps/dav/opt/nvidia-mps/mps_bash </directive>
CISL has integrated the MPS into PBS scheduler. So we could turn on MPS by adding `mps=1` to the PBS resource `-l select=....`, which is the next line. This temporary solution is no longer needed.

2022-11-03 15:42 UTC, sjsprecious commented on machines/config_machines.xml
>          <command name="load">cuda/11.0.3</command>
I later realized that the `nvhpc` module already comes with CUDA. So we probably did not need to load CUDA manually unless the newer CUDA version had a problem. May be worth testing it.

2022-11-03 15:42 UTC, sjsprecious commented on machines/config_machines.xml
>          <command name="load">netcdf/4.8.1</command>
Shall we delete the lines 497 to 505?

2022-11-03 15:42 UTC, sjsprecious commented on machines/config_machines.xml
>        <modules compiler="pgi" mpilib="openmpi" DEBUG="TRUE">
Shall we delete the PGI related settings for Casper now?

2022-11-03 15:42 UTC, sjsprecious commented on machines/config_machines.xml
> +    <CCSM_CPRNC>$ENV{CESMDATAROOT}/tools/cime/tools/cprnc/cprnc</CCSM_CPRNC>
remove `pgi` and `*-gpu` at line 413.

2022-11-03 15:47 UTC, jedwards4b commented on machines/cmake_macros/nvhpc_casper.cmake
> +endif()
I disagree with adding an error message and exiting - we want users to be able to expand the list of supported compilers, machines and offload options.   I can look into adding a warning.

Yes we can add the a100 options.

2022-11-03 15:50 UTC, jedwards4b commented on machines/config_machines.xml
>          <command name="load">cuda/11.0.3</command>
already tested - on casper the cuda module seems to be required even though it shouldn't be

2022-11-03 15:59 UTC, jedwards4b commented on machines/config_machines.xml
> +    <CCSM_CPRNC>$ENV{CESMDATAROOT}/tools/cime/tools/cprnc/cprnc</CCSM_CPRNC>
I know I haven't completed the cleanup here yet.

2022-11-03 16:03 UTC, sjsprecious commented on machines/cmake_macros/nvhpc_casper.cmake
> +endif()
So my concern is that saying we specify V100 GPU and OpenMP offload here, the codes will still compile but no GPU flags are actually applied, which is confusing to me. By adding an error message, we can force a user to add the correct options before the code can be compiled. What do you think?

2022-11-03 16:05 UTC, sjsprecious commented on machines/config_machines.xml
>          <command name="load">cuda/11.0.3</command>
Aha, I see. In this case, can we upgrade the CUDA version to `11.6` since that is the version coming with `nvhpc/22.2`?

2022-11-03 16:09 UTC, sjsprecious requested changes

2022-11-03 16:09 UTC, sjsprecious commented on machines/cmake_macros/nvhpc.cmake
> +if (GPU_TYPE STREQUAL a100 AND GPU_OFFLOAD STREQUAL OpenACC)
Replace `OpenACC` with `OpenMP`.

2022-11-03 16:09 UTC, sjsprecious commented on machines/cmake_macros/nvhpc.cmake
> +if (GPU_TYPE STREQUAL a100 AND GPU_OFFLOAD STREQUAL OpenACC)
Replace `OpenACC` with `OpenMP`.

2022-11-03 16:26 UTC, jedwards4b commented on machines/cmake_macros/nvhpc_casper.cmake
> +endif()
I think that I can enforce this by making the MAX_GPUS_PER_NODE variable in config_machines.xml compiler dependent. How does that sound?

2022-11-03 16:30 UTC, jedwards4b commented on machines/config_batch.xml
>        <directive default="/bin/bash" > -S /glade/u/apps/dav/opt/nvidia-mps/mps_bash </directive>
can the mps=1 be added to the nvhpc select regardless of whether gpus are actually used or should it only be there for gpu cases?

2022-11-03 16:37 UTC, sjsprecious commented on machines/config_batch.xml
>        <directive default="/bin/bash" > -S /glade/u/apps/dav/opt/nvidia-mps/mps_bash </directive>
Great question and I do not know. For safety, can we add the `ngpus` and `mps` options only when `GPU_OFFLOAD` method is not `none`?

2022-11-03 16:44 UTC, sjsprecious commented on machines/config_batch.xml
>        <directive default="/bin/bash" > -S /glade/u/apps/dav/opt/nvidia-mps/mps_bash </directive>
And we have the `ngpus_per_node` option for `create_newcase` script. That could also be used to determine if a job should be submitted to a GPU queue or not, and what PBS resources should be selected later.

2022-11-03 16:48 UTC, sjsprecious commented on machines/cmake_macros/nvhpc_casper.cmake
> +endif()
Oh, I did not realize that you had provided a full list of combinations for OpenACC and OpenMP offload. In this case, my concern is probably unnecessary anymore.

2023-05-26 20:59 UTC, sjsprecious requested changes
Thanks @jedwards4b for issuing this PR. It generally looks good to me but I have some clarifications / change requests before approving it.

2023-05-26 20:59 UTC, sjsprecious commented on machines/config_machines.xml
> +        <command name="load">cuda/11.6</command>
shall we only load the CUDA module when `gpu_offload` is not None? Or `gpu_enabled` is False?

2023-05-26 20:59 UTC, sjsprecious commented on machines/config_machines.xml
> +    <GPU_TYPES>v100,a100</GPU_TYPES>
Shall we specify `gpu_offload` variable as well? For machine with AMD GPUs, `openacc` and `combined` may not be a valid input.

2023-05-26 20:59 UTC, sjsprecious commented on machines/config_machines.xml
> +    <GPU_TYPES>a100</GPU_TYPES>
The same question about `gpu_offload` variable.

2023-05-26 20:59 UTC, sjsprecious commented on machines/config_machines.xml
>        <executable>mpiexec</executable>
At line 1838, shall we do `purge` first before loading any module?

2023-05-26 20:59 UTC, sjsprecious commented on machines/config_batch.xml
> +    <directives queue="casper" compiler="nvhpc" gpu_enabled="true">
I know this works but I am not sure how `gpu_enabled` actually works. Is it an XML variable defined somewhere? And how is it set to True or False during the build. A brief explanation will be very helpful.

2023-05-26 21:09 UTC, jedwards4b commented on machines/config_batch.xml
> +    <directives queue="casper" compiler="nvhpc" gpu_enabled="true">
This is done here: https://github.com/jedwards4b/cime/blob/add_gpu_gust/CIME/case/case.py#L457

gpu_enabled is an attribute of the case object and is set to true if GPU_TYPE is set to a valid value.

2023-05-26 21:10 UTC, jedwards4b commented on machines/config_machines.xml
>        <executable>mpiexec</executable>
This is a feature of modules on gust (and soon derecho) - the two modules loaded above the purge are sticky and not affected by the purge command.

2023-05-26 21:16 UTC, jedwards4b commented on machines/config_machines.xml
> +    <GPU_TYPES>v100,a100</GPU_TYPES>
How do we handle fortran do concurrent here?

2023-05-30 03:22 UTC, sjsprecious commented on machines/config_machines.xml
> +    <GPU_TYPES>v100,a100</GPU_TYPES>
This is a great question! In this case, `combined` may be a confusing word, too. Is there any plan to introduce `do concurrent` to CAM in the future?

2023-05-30 03:23 UTC, sjsprecious commented on machines/config_machines.xml
>        <executable>mpiexec</executable>
Thanks for the clarification. That is clear to me now.

2023-05-30 03:41 UTC, sjsprecious commented on machines/config_batch.xml
> +    <directives queue="casper" compiler="nvhpc" gpu_enabled="true">
Thanks @jedwards4b for the details. That is very helpful!

2023-10-17 15:46 UTC, closed without merging